#Parameters specific to the VK ice core
age_top_prior: -50. #age at the top of the sequence
age_top_sigma: 10. #Error on top age
depth_grid: #depth grid for the age calculation
    type: 'regular'
    start: &depth_start 0.
    end: &depth_end 3501.
    nb_steps: 3501
age_truncation:
    inf: 0.
    sup: 450000.1