LIST_SITES: ['EDC','VK','TALDICE','EDML','NGRIP', 'MSD']

OPT_METHOD: 'leastsq'  #leastsq, leastsq-parallel, none
NB_NODES: 6         #Number of nodes for the leastsq-parallel mode

#Defines the colors for the graphs
COLOR_OBS: 'r'       #color for the observations
COLOR_OPT: 'k'       #color for the posterior scenario
COLOR_MOD: 'b'       #color for the prior scenario
COLOR_CI: '0.8'      #color for the confidence intervals
COLOR_SIGMA: 'm'     #color for the uncertainty
COLOR_DI: 'g'        #color for the dated intervals
SHOW_INITIAL: False  #always put to False for now
COLOR_INIT: 'c'      #always put to 'c' for now
SCALE_AGECI: 10.     #scaling of the confidence interval in the ice and air age figures
SHOW_FIGURES: False  #whether to show or not the figures at the end of the run
SHOW_AIRLAYERTHICK: True #whether to show the air layer thickness figure (buggy on anaconda)
